# Base docker build
FROM sonic-slave-bullseye:bcaf48cc928

# Copy the cache data to host
From scratch as output
COPY --from=sonic-slave-bullseye:bcaf48cc928 /cache.tgz cache.tgz

# Clean up the cache data
FROM sonic-slave-bullseye:bcaf48cc928 as final
RUN rm /cache.tgz

